### ISSUE TITLE
unit test fails for linked list

### ISSUE THREAD

**Issue by JHenneberg** [dongli/fortran-container#1]
Hey Dongli,

I have some troubles with the "linked list". The unit test fails. You have the same problem?

```
/////// Report of Suite: Default test suite, Case: Test linked list type ////////

 +-> Test linked list type: 13 of 14 assertions succeed.
 |   |
 |   +-> Assertion #13 failed with reason: x () == y (bar)
 |   +-> Check line: linked_list_test.F90:44

```

but i couldnt find out the reason yet.

**Comment by dongli** [comment]
I have updated `fortran-unit-test` lib, and run the test successfully:
```
$ ./linked_list_test

/////// Report of Suite: Default test suite, Case: Test linked list type ////////

 +-> Test linked list type: 14 of 14 assertions succeed.
```

I think it is an issue with Intel compiler. Could you investigate further in your case?

**Comment by JHenneberg** [comment]
I will recheck again the next days

**Comment by JHenneberg** [comment]
I fixed the bug and found a mysterious other bug

**Comment by dongli** [comment]
Thanks for testing! What is the other bug?

**Comment by JHenneberg** [comment]
not in the library. I was just wondering how the programm can compile when val is not even declarded in your version of the program (implicit non is used). Should not be possible.

**Comment by dongli** [comment]
It seems `select type` only accept simple expression, not `type` member variable.
